language: java
sudo: required
dist: trusty
install: ""
script: ./gradlew clean check
branches:
    only:
        - master
jdk:
    - openjdk8
cache:
    directories:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
