on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 14]
      fail-fast: false
    steps:
      - uses: "actions/checkout@master"
      - uses: "actions/setup-java@master"
        with:
          java-version: ${{ matrix.java }}
      - uses: gradle/wrapper-validation-action@v1
      - name: "Gradle check"
        run: "./gradlew check"
